var searchData=
[
  ['name_0',['name',['../classrtabmap_1_1CameraModel.html#aa152828f20e1cf0ffab7bb25178191b5',1,'rtabmap::CameraModel::name()'],['../classrtabmap_1_1StereoCameraModel.html#ae759fe4ff0862f5305cf85257e0367a1',1,'rtabmap::StereoCameraModel::name()']]],
  ['nms_1',['NMS',['../namespacertabmap_1_1util2d.html#aafa9a426c8e7dd0359adf40e1b45ee1c',1,'rtabmap::util2d']]],
  ['nnstrategyname_2',['nnStrategyName',['../classrtabmap_1_1VWDictionary.html#a7092a6a6af93772ce89793c5e54a17cc',1,'rtabmap::VWDictionary']]],
  ['normalfiltering_3',['normalfiltering',['../group__PointNormalFiltering.html#ga7c7e3de2ff24fc3aadfb3eb0ae05314d',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZ &gt;::Ptr &amp;cloud, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#gad37b605f0f26190c95450c878ca51ece',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZRGB &gt;::Ptr &amp;cloud, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#gabfeacf2f8a261abd98a9c6728f02324b',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZ &gt;::Ptr &amp;cloud, const pcl::IndicesPtr &amp;indices, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#ga5c15577ccd70487c3ccd53c16b00648b',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZRGB &gt;::Ptr &amp;cloud, const pcl::IndicesPtr &amp;indices, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#gad821858315d7e1e1868d6314d65a9f89',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZI &gt;::Ptr &amp;cloud, const pcl::IndicesPtr &amp;indices, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#ga96711db9864b121ab9e2bcbf2cf44658',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointNormal &gt;::Ptr &amp;cloud, const pcl::IndicesPtr &amp;indices, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#ga91fd9701dea9ebc4b7265b12b357aba1',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZRGBNormal &gt;::Ptr &amp;cloud, const pcl::IndicesPtr &amp;indices, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)'],['../group__PointNormalFiltering.html#gae3831a32e21738a381ea789e9e3e3996',1,'rtabmap::util3d::normalFiltering(const pcl::PointCloud&lt; pcl::PointXYZINormal &gt;::Ptr &amp;cloud, const pcl::IndicesPtr &amp;indices, float angleMax, const Eigen::Vector4f &amp;normal, int normalKSearch, const Eigen::Vector4f &amp;viewpoint, float groundNormalsUp=0.0f)']]],
  ['normalizerotation_4',['normalizeRotation',['../classrtabmap_1_1Transform.html#acbdd19971643c7400cb59055ec64d3cf',1,'rtabmap::Transform']]],
  ['now_5',['now',['../classUTimer.html#ad10fce2a4901bf5d6a460ca7b158cb3a',1,'UTimer']]]
];
