function [Data] = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 07-Oct-2009 10:10:26

% Import the file
rawData1 = importdata(fileToRead1);

if isstruct(rawData1) 
    rawData1=rawData1.data; 
end 

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[unused,name] = fileparts(fileToRead1); %#ok
newData1.(genvarname(name)) = rawData1;

vars = fieldnames(newData1);
if length(vars) > 0
    Data = newData1.(vars{1});
end

