# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: '^build/|^data/|^app/|^archive/|^cmake_modules/|^\..*'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    -   id: cmake-format
    -   id: cmake-lint

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.1
    hooks:
    -   id: clang-format
        args: ["-style=Google", "-i"]
        
