cmake_minimum_required(VERSION 3.16)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(rtabmap_gtsam_sigmoid LANGUAGES CXX)
    set(CMAKE_CXX_STANDARD 17)
    enable_testing()
    find_package(GTSAM CONFIG REQUIRED)
endif()
add_executable(test_gtsam_sigmoid test_gtsam_sigmoid.cpp)
target_link_libraries(test_gtsam_sigmoid PRIVATE gtsam)
add_test(NAME test_gtsam_sigmoid COMMAND test_gtsam_sigmoid)
